# Generated by Django 5.1.6 on 2025-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_candidate_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
